config/routes.rb
Rails.application.routes.draw do
  
  root to: 'users#index'
  devise_for :users
  resources :users
  resources :posts
  resources :posts do
    resources :likes
    resources :comments
  end
  resources :friendships , only: [:create, :destroy,:update]
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 200,
                                                too_long: '200 characters in comment is the maximum allowed.' }

  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
  validates :user_id, exclusion: { in: ->(friendship) { [friendship.friend_id] } }
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :post_id }

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { maximum: 1000,
                                                too_long: '1000 characters in post is the maximum allowed.' }

  belongs_to :user

  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/models/user.rb
# rubocop:disable Lint/Void

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :email, presence: true, length: { maximum: 20 }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'
  has_many :confirmed_friendships, -> { where confirmed: true }, class_name: 'Friendship'
  has_many :friends, through: :confirmed_friendships
  has_many :pending_friendships, -> { where confirmed: nil }, class_name: 'Friendship', foreign_key: 'user_id'
  has_many :pending_friends, through: :pending_friendships, source: :friend
  has_many :inverted_friendships, -> { where confirmed: nil }, class_name: 'Friendship', foreign_key: 'friend_id'
  has_many :friend_requests, through: :inverted_friendships, source: :user

  def friends
    friends_array = friendships.map { |friendship| friendship.friend if friendship.confirmed }
    friends_array + inverse_friendships.map { |friendship| friendship.user if friendship.confirmed }
    friends_array.compact
  end

  # Users who have yet to confirme friend requests
  def pending_friends
    friendships.map { |friendship| friendship.friend unless friendship.confirmed }.compact
  end

  def confirm_friend(user)
    friendship = inverse_friendships.find { |i| i.user.id == user }
    friendship.confirmed = true
    friendship.save
    Friendship.create(user_id: friendship.friend_id, friend_id: friendship.user_id, confirmed: true)
  end

  def friend?(user)
    friends.include?(user)
  end
end

# rubocop:enable Lint/Void

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def authenticate_friends
    @user = User.find(params[:id])
    return if current_user.friend?(@user) || @user == current_user

    redirect_to users_path, notice: 'Users profile is private!'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user = current_user

    if @comment.save
      redirect_to posts_path, notice: 'Comment was successfully created.'
    else
      redirect_to posts_path, alert: @comment.errors.full_messages.join('. ').to_s
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = Friendship.new(user_id: current_user.id, friend_id: friendship_params[:friend_id])
    # @reverse_friendship = Friendship.new(friend_id: current_user.id, user_id: friendship_params[:friend_id])
    if @friendship.valid?
      @friendship.save
    else
      flash[:warning] = 'Error sending friend request'
    end
    redirect_to users_path
  end

  def update
    @friendship = Friendship.find_by(user_id: params[:friend_id].to_i, friend_id: current_user.id)
    if current_user.confirm_friend(@friendship.user.id)
      flash[:success] = 'friend request accepted'
    else
      flash[:warning] = 'error accepting friend request'
    end
    redirect_to user_path
  end

  def destroy
    @friendship = Friendship.find_by(user_id: params[:friend_id].to_i, friend_id: current_user.id)
    if @friendship.delete
      flash[:success] = 'friend request declined'
    else
      flash[:warning] = 'error declining friend request'
    end
    redirect_to user_path
  end

  private

  def friendship_params
    params.permit(:friend_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(post_id: params[:post_id])

    if @like.save
      redirect_to posts_path, notice: 'You liked a post.'
    else
      redirect_to posts_path, alert: 'You cannot like this post.'
    end
  end

  def destroy
    like = Like.find_by(id: params[:id], user: current_user, post_id: params[:post_id])
    if like
      like.destroy
      redirect_to posts_path, notice: 'You disliked a post.'
    else
      redirect_to posts_path, alert: 'You cannot dislike post that you did not like before.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = Post.new
    timeline_posts
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      timeline_posts
      render :index, alert: 'Post was not created.'
    end
  end

  private

  def timeline_posts
    @timeline_posts ||= Post.all.ordered_by_most_recent.includes(:user)
  end

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_friends, only: :show

  def index
    @users = User.all.includes(:friendships).to_a
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.ordered_by_most_recent
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_link_to(link_text, link_path)
    class_name = current_page?(link_path) ? 'menu-item active' : 'menu-item'

    content_tag(:div, class: class_name) do
      link_to link_text, link_path
    end
  end

  def like_or_dislike_btn(post)
    like = Like.find_by(post: post, user: current_user)
    if like
      link_to('Dislike!', post_like_path(id: like.id, post_id: post.id), method: :delete)
    else
      link_to('Like!', post_likes_path(post_id: post.id), method: :post)
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def pending_friend?(user)
    current_user.pending_friends.include?(user) || current_user.friend_requests.include?(user)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorSocialScaffold</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="nav">
      <%= link_to 'Stay in touch', root_path %>
      <div class="menu">
        <div class="menu-item">
          <%= menu_link_to 'Timeline', posts_path %>
        </div>
        <div class="menu-item">
          <%= menu_link_to 'All users', users_path %>
        </div>
      </div>
      <%unless current_user.nil?%>
        <%= link_to "#{current_user.name}'s Profile", current_user,:class=>"mr-2" %>
      <%end%>
      <% if current_user %>
        <%= link_to " #{current_user.name} Sign out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign in', user_session_path %>
      <% end %>
    </nav>
    <% if notice.present? %>
      <div class="notice">
        <p> <%= notice %> </p>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert">
        <p> <%= alert %> </p>
      </div>
    <% end %>
    <main class="main">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_post.html.erb
<li class="post">
  <div>
    <div class='post-attribution' >
      <%= link_to post.user.name, user_path(post.user), class: 'post-author' %>
    </div>
    <div class='post-liking'>
      <span class='post-date'> <%= post.created_at.strftime("%Y/%m/%d") %> </span>
      <%= like_or_dislike_btn(post) %>
    </div>
  </div>
  <p class="post-content">
    <%= post.content %>
  </p>

  <div class='post-comments-section'>
    <% post.comments.each do |comment| %>
      <div class="post-comments">
        <p>
          <b><%= comment.user.name %>:</b> <%= comment.content %>
        </p>
        <span> <%= comment.created_at.strftime("%Y/%m/%d") %> </span>
      </div>
    <% end %>

    <%= form_for(post.comments.new, url: post_comments_path(post)) do |form| %>
      <%= form.text_field :content, id: :comment_content, class: 'form-control', placeholder: 'Add new Comment' %>
      <%= form.submit 'Comment', class: 'btn btn-secondary' %>
    <% end %>
  </div>
</li>

app/views/posts/index.html.erb
<%= form_for(@post) do |form| %>
  <%= form.label :content %>
  <%= form.text_field :content, id: :post_content, class: 'form-control', placeholder: 'Add New Post' %>
  <% if @post.errors.full_messages.any? %>
    <p class="errors">
      <%= "Post could not be saved. #{@post.errors.full_messages.join('. ')}" %>
    </p>
  <% end %>
  <%= form.submit 'Save', class: 'btn btn-primary' %>
<% end %>

<article class="timeline">
  <h3>
    Recent posts
  </h3>
  <ul class="posts">
    <%= render @timeline_posts %>
  </ul>
</article>

app/views/shared/_errors.html.erb
      <% flash.each do |message_type, message| %>
        <div class="text-center alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

app/views/users/index.html.erb
<%=console if Rails.env == "development"%>
<%=render 'shared/errors'%>
<section class="users-section">
  <ul class="users-list">
    <% @users.each do |user| %>
      <li>
        Name: <%= user.name %>
        <span class="profile-link">
          <%= link_to 'See Profile',  user_path(user), class: 'profile-link' %>
          <%if !current_user.friend?(user) &&  current_user != user && !pending_friend?(user) %>
              <%= link_to 'Send Friend Request',  friendships_path(friend_id:user.id), class: 'btn btn-primary', method:"post" %>
            <%elsif current_user != user && !current_user.friends  %>
             <a href="#" class="btn btn-secondary  disabled" role="button" aria-disabled="true">Pending</a>
          <%end%>
        </span>
      </li>
    <% end %>
  </ul>
</section>

app/views/users/show.html.erb
<%=console if Rails.env == "development"%>
<section class="user-section">
  <h2><%= "Name: #{@user.name}" %></h2>
  <article class="timeline">
    <h3>Recent posts:</h3>
    <ul class="posts">
      <%= render @posts %>
    </ul>
  </article>
</section>

<div class="d-flex">
  <section class="user-section mx-3">
  <h2>friends</h2>
  <ul class="posts">
  <%@user.friends.each do |friendship|%>
  <li><%=friendship.name.capitalize%></li>
  <%end%>
  </ul>
  </section>
  <%if current_user == @user %>
      <section class="user-section text-nowrap">
    <ul>
      <h2>pending friends</h2>
      <%current_user.pending_friends.each do |friend|%>
            <li>
              <%=friend.name.capitalize%>
            </li>
      <%end%>
      </ul>
    </section>
    <section class="user-section text-nowrap">
    <ul>
      <h2>Friend requests</h2>
      <%current_user.friend_requests.each do |friend|%>
            <li>
              <%=friend.name.capitalize%>
              <%= link_to 'Accept Friend Request',  friendship_path(friend_id:friend.id), class: 'btn btn-primary', method:"patch" %>
              <%= link_to 'Decline Friend Request',  friendship_path(friend_id:friend.id), class: 'btn btn-danger', method:"delete" %>
            </li>
      <%end%>
      </ul>
    </section>
  <%end%>
</div>